id: IDD44DFD5
legacy_id: P010442
ocr_import_info:
  bdrc_scan_id: W00EGS1016770
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T12:27:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T12:57:14.073494+00:00'
last_modified: 2022-08-30 20:57:34.125862
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016770
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016770
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཡང་སྒྲུབ་ནོར་བུ་མཆོག་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.8068781746924344
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I01JW32:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW32
      total_pages: 160
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW32.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8068781746924344
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
