id: P010442
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00EGS1016770
  title: གཡང་སྒྲུབ་ནོར་བུ་མཆོག་རྒྱལ
  author: ''
  volumes:
    9d527d2cbc8b405ea34925304013f03c:
      image_group_id: I01JW32
      title: ''
      volume_number: 1
      total_pages: 160
      base_file: v001.txt
